
apiVersion: v1
kind: Service
metadata:
  #The name of the Kubernetes Service to be created 
  #in the Kubernetes cluster
  name: my-service 
spec:
  selector:
    app: spring-boot-cicd 
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 8083 #Service port
    targetPort: 8083 #The port for the React.js application container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment #The name of the Kubernetes 
        #Deployment to be created in the Kubernetes cluster
  labels:
    app: spring-boot-cicd
spec:
  replicas: 2 #The number of pods to be created in the 
   #Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: spring-boot-cicd
  template:
    metadata:
      labels:
        app: spring-boot-cicd 
    spec:
      containers:
      - name: spring-boot-cicd #The name of the react.js application container
        #The Docker image for building the React.js application container
        image: andrews/spring-boot-cicd:latest 
        ports:
        - containerPort: 8083 #The port for the React.js application container