apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-cicd        
  labels:
    app: spring-boot-cicd
spec:
  replicas: 2   
  selector:
    matchLabels:
      app: spring-boot-cicd
  template:
    metadata:
      labels:
        app: spring-boot-cicd 
    spec:
      containers:
      - name: spring-boot-cicd        
        image: andrews/spring-boot-cicd:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
---        
apiVersion: v1
kind: Service
metadata:
  #The name of the Kubernetes Service to be created 
  #in the Kubernetes cluster
  name: spring-boot-cicd
spec:
  selector:
    app: spring-boot-cicd 
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 8090 #Service port
    targetPort: 8090 #The port for the React.js application container